apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sx-kargo
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/suxess-it/sx-cnp-oss
    targetRevision: main
    path: platform-apps/charts/kargo
    helm:
      valueFiles:
      - values-k3d.yaml
  destination:
    namespace: kargo
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
