apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sx-team-onboarding
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/suxess-it/sx-cnp-oss
    targetRevision: main
    path: platform-apps/charts/team-onboarding
    helm:
      valueFiles:
      - values-k3d.yaml
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
