apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: kargo-project-name-validation
  annotations:
    policies.kyverno.io/title: Kargo Project Name Validation
    policies.kyverno.io/category: Kargo
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Kargo Project
    kyverno.io/kyverno-version: 1.6.0
    policies.kyverno.io/minversion: 1.6.0
    kyverno.io/kubernetes-version: "1.23"
    policies.kyverno.io/description: >-
      This policy checks if the Kargo Project Name matches with the allowed destinations
      in the corresponding ArgoCD Project.
spec:
  validationFailureAction: audit
  background: true
  rules:
  - name: check-kargo-project-name
    skipBackgroundRequests: true
    match:
      any:
      - resources:
          kinds:
          - Project
    context:
    - name: app_namespace
      variable:
        jmesPath: request.object.metadata.labels."argocd.argoproj.io/instance" |  split(@, '_') | [0]
    - name: app
      variable:
        jmesPath: request.object.metadata.labels."argocd.argoproj.io/instance" |  split(@, '_') | [1]
    - name: argocd_project
      apiCall:
        method: GET
        urlPath: "/apis/argoproj.io/v1alpha1/namespaces/{{`{{app_namespace}}`}}/applications/{{`{{app}}`}}"
        jmesPath: spec.project
    - name: allowed_destination
      apiCall:
        method: GET
        urlPath: "/apis/argoproj.io/v1alpha1/namespaces/argocd/appprojects/{{`{{argocd_project}}`}}"
        jmesPath: spec.destinations[].namespace
    validate:
      message: >-
        Kyverno project '{{`{{request.object.metadata.name}}`}}' doesn't match the
        allowed destination '{{`{{allowed_destination}}`}}'
        of the argocd project '{{`{{argocd_project}}`}}'
        referenced in application '{{`{{app}}`}}'
        in namespace '{{`{{app_namespace}}`}}'
      deny:
        conditions:
          all:
          - key: "{{`{{request.object.metadata.name}}`}}"
            operator: AnyNotIn
            value: "{{`{{allowed_destination}}`}}"