{{- if .Values.cert.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-server-certificate
spec:
  secretName: argocd-server-tls
  issuerRef:
    name: {{ .Values.cert.issuerRef }}
    kind: ClusterIssuer
  dnsNames:
    - {{ .Values.cert.dnsName }}
{{- end }}
