apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: cert-manager
  title: cert-manager
  description: cert-manager Instance für sx-cnp-oss
  links: 
    - url: https://cert-manager.io
      title: Official Documentation
      icon: web
spec:
  type: cert-manager
  lifecycle: production
  owner: sx-cnp-oss
  system: sx-cnp-oss