apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: kyverno
  title: kyverno
  description: kyverno Instance for sx-cnp-oss
  links: 
    - url: https://kyverno.io/
      title: Official Documentation
      icon: web
spec:
  type: policy-management
  lifecycle: production
  owner: sx-cnp-oss
  system: sx-cnp-oss