apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: tempo
  title: tempo
  description: tempo Instance fpr sx-cnp-oss 
  links: 
    - url: https://grafana.com/docs/tempo/latest/
      title: Official Documentation
      icon: web
spec:
  type: observability
  lifecycle: production
  owner: sx-cnp-oss
  system: sx-cnp-oss