# applies to podtato-head-entry deployment only
ingress:
  hosts:
    - host: kargo-qa-${{values.application_id}}-${{values.fqdn}}
      paths:
        - path: /
          pathType: ImplementationSpecific