k8s-monitoring:

  alloy:
    logging:
      # -- Level at which Alloy log lines should be written.
      # @section -- Deployment: [Alloy](https://github.com/grafana/alloy/tree/main/operations/helm/charts/alloy)
      level: info

  cluster:
    name: "suxessit-uibklab-jokl"
  
  externalServices:
    prometheus:
      host: "http://sx-mimir-nginx.mimir.svc"
      queryEndpoint: "/prometheus/api/v1/query"
      writeEndpoint: "/api/v1/push"
      tenantId: ""
    loki:
      host: "http://sx-loki-gateway.loki.svc"
      queryEndpoint: "/loki/api/v1/query"
      writeEndPoint: "/loki/api/v1/push"
      tenantId: ""

  opencost:
    enabled: false

  metrics:
    apiserver:
      enabled: true
      metricsTuning:
        includeMetrics:
          - apiserver_requested_deprecated_apis
          - apiserver_request_total
          - apiserver_request_duration_seconds_sum
          - apiserver_request_duration_seconds_count
          - workqueue_depth
          - process_cpu_seconds_total
          - process_resident_memory_bytes
          - apiserver_requested_deprecated_apis
    kube-state-metrics:
      metricsTuning:
        includeMetrics:
          - kube_namespace_created
          - kube_namespace_labels
          - kube_pod_container_status_running
          - kube_service_info
          - kube_endpoint_info
          - kube_ingress_info
          - kube_deployment_labels
          - kube_statefulset_labels
          - kube_daemonset_labels
          - kube_persistentvolumeclaim_info
          - kube_hpa_labels
          - kube_configmap_info
          - kube_secret_info
          - kube_networkpolicy_labels
          - kube_node_info
    cadvisor:
      metricsTuning:
        includeMetrics:
          - machine_cpu_cores
          - container_oom_events_total
          - container_cpu_cfs_throttled_seconds_total

  extraConfig: |
    mimir.rules.kubernetes "rules" {
      address = nonsensitive(remote.kubernetes.secret.metrics_service.data["host"])
      tenant_id = "anonymous"

      rule_namespace_selector {
          match_labels = {
            "kubernetes.io/metadata.name" = "k8s-monitoring",
          }
      }
      rule_selector {
          match_labels = {}
      }
    }

    discovery.relabel "coredns" {
      targets = discovery.kubernetes.pods.targets
      rule {
        source_labels = ["__meta_kubernetes_pod_label_k8s_app"]
        regex = "kube-dns"
        action = "keep"
      }
      rule {
        source_labels = ["__meta_kubernetes_pod_container_port_number"]
        regex = "9153"
        action = "keep"
      }
      rule {
        source_labels = ["__meta_kubernetes_pod_name"]
        target_label = "instance"
      }
    }
    prometheus.scrape "coredns" {
      job_name     = "integrations/coredns"
      targets      = discovery.relabel.coredns.output
      honor_labels = true
      forward_to   = [prometheus.relabel.metrics_service.receiver]
    }
