k8s-monitoring:
  cluster:
    name: "sx-cnp-oss-kind"
  
  externalServices:
    prometheus:
      host: "http://sx-mimir-nginx.mimir.svc"
      queryEndpoint: "/prometheus/api/v1/query"
      writeEndpoint: "/api/v1/push"
      tenantId: ""
    loki:
      host: "http://sx-loki-gateway.loki.svc"
      queryEndpoint: "/loki/api/v1/query"
      writeEndPoint: "/loki/api/v1/push"
      tenantId: ""

  opencost:
    enabled: false

  metrics:
    kube-state-metrics:
      metricsTuning:
        includeMetrics:
          - kube_namespace_created

  extraConfig: |
    mimir.rules.kubernetes "rules" {
      address = nonsensitive(remote.kubernetes.secret.metrics_service.data["host"])
      tenant_id = ""

      rule_namespace_selector {
          match_labels = {
              name = "k8s-monitoring",
          }
      }
    }
