teams:
  - name: team1
    sourceRepos:
      - '*'
    clusterResourceWhitelist:
      - group: ""
        kind: Namespace
      # also allow kargo Project cluster resource,
      # all details why is documented currently in
      # https://github.com/akuity/kargo/issues/2058
      - group: kargo.akuity.io
        kind: Project
    appOfAppsRepo:
      repoURL: https://github.com/suxess-it/team1-apps
      path: k3d-apps
      revision: main
  - name: team2
    sourceRepos:
      - '*'
    clusterResourceWhitelist:
      - group: ""
        kind: Namespace
      - group: kargo.akuity.io
        kind: Project
    appOfAppsRepo:
      repoURL: https://github.com/suxess-it/team2-apps
      path: k3d-apps
      revision: main
    # in the future maybe also some attributes for an scm / git application-set instead of appOfApps possible
    scmAppSet: ~
    gitAppSet: ~

argo-cd:
  global:
    domain: argocd-127-0-0-1.nip.io

  configs:
    params:
      server.insecure: true
      application.namespaces: "team1-apps,team2-apps"
      applicationsetcontroller.namespaces: "team1-apps,team2-apps"
      applicationsetcontroller.allowed.scm.providers: https://github.com/
    secret:
      createSecret: false

    cm:
      accounts.backstage: apiKey

      resource.customizations: |
        argoproj.io/Application:
          health.lua: |
            hs = {}
            hs.status = "Progressing"
            hs.message = ""
            if obj.status ~= nil then
              if obj.status.health ~= nil then
                hs.status = obj.status.health.status
                if obj.status.health.message ~= nil then
                  hs.message = obj.status.health.message
                end
              end
            end
            return hs

    rbac:
      policy.csv: |
        p, backstage, applications, get, */*, allow

  server:
    ingress:
      enabled: true
      annotations: 
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      extraTls:
        - hosts:
          - argocd-127-0-0-1.nip.io
          # Based on the ingress controller used secret might be optional
          secretName: argocd-server-tls
    extensions:
      enabled: true
      contents:
        - name: argo-rollouts
          url: https://github.com/argoproj-labs/rollout-extension/releases/download/v0.3.4/extension.tar

  applicationSet:
    allowAnyNamespace: true
