apiVersion: v1
data:
  admin.password: JDJhJDEwJHUvcElERzFxdXV0R09XZlZXT0hNbk9QaVljbDVTNzl6L01ZZHhNVGk4dGNQWmhCQ3dhRHZL
  admin.passwordMtime: MjAyNC0wNC0wOFQyMjozMDo0N1o=
  server.secretkey: MGczWjBiM2xybTdGYkYwTm5ubTdKTnQvbkpFaEx3Y0FEL1V6bytQakRETT0=
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
  name: argocd-secret
  namespace: argocd
type: Opaque
