alloy:
  ## Various Alloy settings. For backwards compatibility with the grafana-agent
  ## chart, this field may also be called "agent". Naming this field "agent" is
  ## deprecated and will be removed in a future release.
  alloy:
    configMap:
      # -- Content to assign to the new ConfigMap.  This is passed into `tpl` allowing for templating from values.
      content: |
        logging {
          level  = "info"
          format = "logfmt"
        }

        loki.source.kubernetes_events "events" {
          log_format = "json"
          forward_to = [loki.write.loki_endpoint.receiver]
        }

        loki.write "loki_endpoint" {
          endpoint {
            url = "http://loki:3100/loki/api/v1/push"
          }
        }
