apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.name }}-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: {{ .Values.name }}-secret
    template:
      data:
        ARGOCD_URL: "{{ `{{ .ARGOCD_URL }}` }}"
        ARGOCD_AUTH_TOKEN: "{{ `{{ .ARGOCD_AUTH_TOKEN }}` }}"
        GITHUB_CLIENTID: "{{ `{{ .GITHUB_CLIENTID }}` }}"
        GITHUB_ORG: "{{ `{{ .GITHUB_ORG }}` }}"
        GITHUB_CLIENTSECRET: "{{ `{{ .GITHUB_CLIENTSECRET }}` }}"
        GITHUB_TOKEN: "{{ `{{ .GITHUB_TOKEN }}` }}"
        K8S_API_URL: "{{ `{{ .K8S_API_URL }}` }}"
        K8S_SA_TOKEN: "{{ `{{ .K8S_SA_TOKEN }}` }}"
        ARGOCD_USERNAME: "{{ `{{ .ARGOCD_USERNAME }}` }}"
        ARGOCD_PASSWORD: "{{ `{{ .ARGOCD_PASSWORD }}` }}"
        ARGOCD_URL_LE: "{{ `{{ .ARGOCD_URL_LE }}` }}"
        GRAFANA_TOKEN: "{{ `{{ .GRAFANA_TOKEN  }}` }}"
        VAULT_TOKEN: "{{ `{{ .VAULT_TOKEN }}` }}"
        VAULT_ADDR: "{{ `{{ .VAULT_ADDR }}` }}"
        RH_IMAGE_REGISTRY_TOKEN: "{{ `{{ .RH_IMAGE_REGISTRY_TOKEN }}` }}"
        RH_IMAGE_REGISTRY_URL: "{{ `{{ .RH_IMAGE_REGISTRY_URL  }}` }}"
        JIRA_TOKEN: "{{ `{{ .JIRA_TOKEN }}` }}"
        JIRA_URL: "{{ `{{ .JIRA_URL }}` }}"
  data:
  - secretKey: ARGOCD_URL
    remoteRef:
      key: {{ .Values.vault.keystore }}/data/{{ .Values.name }}/cnp
      property: ARGOCD_URL
  - secretKey: ARGOCD_AUTH_TOKEN
    remoteRef:
      key: {{ .Values.vault.keystore }}/data/{{ .Values.name }}/cnp
      property: ARGOCD_AUTH_TOKEN
  - secretKey: GITHUB_CLIENTID
    remoteRef:
      key: {{ .Values.vault.keystore }}/data/{{ .Values.name }}/cnp
      property: GITHUB_CLIENTID
  - secretKey: GITHUB_CLIENTSECRET
    remoteRef:
      key: {{ .Values.vault.keystore }}/data/{{ .Values.name }}/cnp
      property: GITHUB_CLIENTSECRET
  - secretKey: GITHUB_TOKEN
    remoteRef:
      key: {{ .Values.vault.keystore }}/data/{{ .Values.name }}/cnp
      property: GITHUB_TOKEN
  - secretKey: K8S_API_URL
    remoteRef:
      key: {{ .Values.vault.keystore }}/data/{{ .Values.name }}/cnp
      property: K8S_API_URL
  - secretKey: K8S_SA_TOKEN
    remoteRef:
      key: {{ .Values.vault.keystore }}/data/{{ .Values.name }}/cnp
      property: K8S_SA_TOKEN
  - secretKey: ARGOCD_USERNAME
    remoteRef:
      key: {{ .Values.vault.keystore }}/data/{{ .Values.name }}/cnp
      property: ARGOCD_USERNAME
  - secretKey: ARGOCD_PASSWORD
    remoteRef:
      key: {{ .Values.vault.keystore }}/data/{{ .Values.name }}/cnp
      property: ARGOCD_PASSWORD
  - secretKey: ARGOCD_URL_LE
    remoteRef:
      key: {{ .Values.vault.keystore }}/data/{{ .Values.name }}/cnp
      property: ARGOCD_URL_LE
  - secretKey: GRAFANA_TOKEN
    remoteRef:
      key: {{ .Values.vault.keystore }}/data/{{ .Values.name }}/cnp
      property: GRAFANA_TOKEN
  - secretKey: VAULT_TOKEN
    remoteRef:
      key: {{ .Values.vault.keystore }}/data/{{ .Values.name }}/cnp
      property: VAULT_TOKEN
  - secretKey: VAULT_ADDR
    remoteRef:
      key: {{ .Values.vault.keystore }}/data/{{ .Values.name }}/cnp
      property: VAULT_ADDR
  - secretKey: RH_IMAGE_REGISTRY_TOKEN
    remoteRef:
      key: {{ .Values.vault.keystore }}/data/{{ .Values.name }}/cnp
      property: RH_IMAGE_REGISTRY_TOKEN
  - secretKey: RH_IMAGE_REGISTRY_URL
    remoteRef:
      key: {{ .Values.vault.keystore }}/data/{{ .Values.name }}/cnp
      property: RH_IMAGE_REGISTRY_URL
  - secretKey: JIRA_TOKEN
    remoteRef:
      key: {{ .Values.vault.keystore }}/data/{{ .Values.name }}/cnp
      property: JIRA_TOKEN
  - secretKey: JIRA_URL
    remoteRef:
      key: {{ .Values.vault.keystore }}/data/{{ .Values.name }}/cnp
      property: JIRA_URL
