apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: kubecost
  title: Kubecost
  description: Kubecost 
  links: 
  {{- if and .Values.ingress .Values.ingress.hosts }}
    {{- range .Values.ingress.hosts }}
    - url: https://{{ . }}
    {{- end }}
  {{- end }}
      title: Kubecost Instance of sx-cnp-oss
      icon: web
    - url: https://docs.kubecost.com
      title: Official Documentation
      icon: web
spec:
  type: cost-provider
  lifecycle: production
  owner: sx-cnp-oss
  system: sx-cnp-oss