{{- range .Values.stages }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $.Values.appName }}-{{ .name }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    kargo.akuity.io/authorized-stage: {{ tpl $.Values.kargoProject $ }}:{{ .name }}
spec:
  project: {{ $.Values.appProject }}
  source:
    repoURL: {{ $.Values.repoUrl }}
    targetRevision: stages/{{ .name }}
    path: .
    helm:
      valueFiles:
      - values-{{ .name }}.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $.Values.appName }}-{{ .name }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- if $.Values.createAppNamespace }}
    syncOptions:
    - CreateNamespace=true
{{- end }}
---
{{- end }}