apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: sx-cnp-oss-kargo-demo-app-template
  title: Template for Kargo Demo App
  description: Run Kargo driven Demo App provisoned with ArgoCD
  tags:
    - kargo
    - metalstack
spec:
  owner: user:phac008
  type: system
  
  parameters:
    - title: Provide information on this application
      required:
        - application_id
        - owner
        - description
        - fqdn
      properties:
        application_id:
          title: Name
          type: string
          description: Unique name of this app
        description:
          title: Description
          type: string
          description: Help others understand what this app is for.
        owner:
          title: Owner
          type: string
          description: Owner of this vm
          ui:field: OwnerPicker
          ui:options:
            allowedKinds: 
              - User
        fqdn:
          title: FQDN
          type: string       
          default: '127-0-0-1.nip.io'
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            requestUserCredentials:
              secretsKey: USER_OAUTH_TOKEN
              additionalScopes:
                github: 
                  - workflow
                  - user
            allowedHosts:
              - github.com
  steps:
    - id: template-gitops
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./kargo-gitops
        targetPath: ./kargo-gitops
        copyWithoutTemplating: 
          - .github/workflows/branch.yaml
        values:
          application_id: ${{ parameters.application_id }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}
          fqdn: ${{ parameters.fqdn }}
          repoUrl: ${{ parameters.repoUrl }}
          repoUrlRepo: ${{ (parameters.repoUrl | parseRepoUrl)["repo"] }}
          repoUrlowner: ${{ (parameters.repoUrl | parseRepoUrl)["owner"] }}

    - id: publish-gitopsreposetup
      name: Publish Template Gitops Repo
      action: publish:github
      input:
        sourcePath: ./kargo-gitops
        allowedHosts: ['github.com']
        description: This is Kargo Demo App ${{ parameters.application_id }}
        repoUrl: ${{ parameters.repoUrl }}
        token: ${{ secrets.USER_OAUTH_TOKEN }}
        fqdn: ${{ parameters.fqdn }}
        repoVisibility: public
        deleteBranchOnMerge: true
        protectDefaultBranch: false
        defaultBranch: main
        
    - id: template-applicationsetup
      name: Fetch Namespacesetup Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton/applicationsetup
        targetPath: ./applicationsetup
        copyWithoutRender: []
        values:
          application_id: ${{ parameters.application_id }}
          description: ${{ parameters.description }}
          repoUrlRepo: ${{ (parameters.repoUrl | parseRepoUrl)["repo"] }}
          repoUrlowner: ${{ (parameters.repoUrl | parseRepoUrl)["owner"] }}
          environments: ${{ parameters.environments }}

#    - id: pull-request-applicationsetup
#      name: make a pr to approved-application repo with additional applicationsetup
#      action: publish:github:pull-request
#      input:
#        sourcePath: ./applicationsetup
#        targetPath: '.'
#        repoUrl: github.com?repo=approved-application&owner=suxess-it
#        branchName: ${{ parameters.application_id }}
#        token: ${{ secrets.USER_OAUTH_TOKEN }}
#        title: argoapps and system config for ${{ parameters.application_id }}
#        description: argoapps and system config for ${{ parameters.application_id }}

    - id: register
      name: Register catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps["publish-gitopsreposetup"].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: Repository
        url: ${{ steps["publish-gitopsreposetup"].output.remoteUrl }}
      - title: Approved-Apps PR
        url: ${{ steps["pull-request-applicationsetup"].output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
