apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: warehouse-{{ .Values.appName }}
  namespace: {{ .Release.Namespace }}
spec:
  subscriptions:
  - git:
      repoURL: {{ .Values.repoUrl }}