mimir:
  nginx:
    ingress:
      enabled: true
      hosts:
        - host: metrics-monitoring-127-0-0-1.nip.io
          paths:
            - path: /
              pathType: Prefix
      tls: ""
  mimir:
    structuredConfig:
      limits:
        max_global_series_per_user: 300000
  