mimir:
  nginx:
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert.gardener.cloud/purpose: managed
        dns.gardener.cloud/class: garden
        dns.gardener.cloud/dnsnames: metrics-monitoring.lab.suxessit.k8s.cloud.uibk.ac.at
        dns.gardener.cloud/ttl: "180"
      hosts:
        - host: metrics-monitoring.lab.suxessit.k8s.cloud.uibk.ac.at
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: mimir-nginx-tls
          hosts:
            - metrics-monitoring.lab.suxessit.k8s.cloud.uibk.ac.at