site_name: sx-cnp-oss
site_description: 'User documentation for sX cnp oss Showcase'
edit_uri: edit/main/docs

plugins:
  - techdocs-core

# Note for content editors, edit only the section below
nav:
  - Overview: index.md
  - Onboard a developer to CNP: onboard-cnp.md
  - Application Migration:
      - Migration Process Steps: application-migration/migration-process.md
      - Learning Path for Developers: application-migration/learning-path.md