
apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: kargo-${{values.application_id}}
spec:
  promotionPolicies:
  - stage: test
    autoPromotionEnabled: true
  - stage: qa
    autoPromotionEnabled: true
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: warehouse-${{values.application_id}}
  namespace: kargo-${{values.application_id}}
spec:
  subscriptions:
  - git:
      repoURL: https://github.com/${{values.repoUrlowner}}/${{values.repoUrlRepo}}.git
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: kargo-${{values.application_id}}
spec:
  subscriptions:
    warehouse: warehouse-${{values.application_id}}
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/${{values.repoUrlowner}}/${{values.repoUrlRepo}}.git
      writeBranch: stages/test
    argoCDAppUpdates:
    - appName: test-${{values.application_id}}
      appNamespace: argocd
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: qa
  namespace: kargo-${{values.application_id}}
spec:
  subscriptions:
    upstreamStages:
    - name: test
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/${{values.repoUrlowner}}/${{values.repoUrlRepo}}.git
      writeBranch: stages/qa
    argoCDAppUpdates:
    - appName: qa-${{values.application_id}}
      appNamespace: argocd
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: kargo-${{values.application_id}}
spec:
  subscriptions:
    upstreamStages:
    - name: qa
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/${{values.repoUrlowner}}/${{values.repoUrlRepo}}.git
      writeBranch: stages/prod
    argoCDAppUpdates:
    - appName: prod-${{values.application_id}}
      appNamespace: argocd
