appProject: team-jokl
appName: team-jokl-demo-app
repoUrl: https://github.com/suxess-it/sx-cnp-oss-demo-app
stages:
  - name: "test"
    subscriptions: 
      warehouse: warehouse-demo-app
  - name: "qa"
    subscriptions: 
      upstreamStages:
      - name: test
  - name: "prod"
    subscriptions: 
      upstreamStages:
      - name: qa