apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-app
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - stage: test
      - stage: qa
      - stage: prod
  template:
    metadata:
      name: {{stage}}-demo-app
      annotations:
        kargo.akuity.io/authorized-stage: kargo-demo-app:{{stage}}
    spec:
      project: default
      source:
        repoURL: https://github.com/suxess-it/sx-cnp-oss-demo-app
        targetRevision: stages/{{stage}}
        path: .
      destination:
        namespace: {{stage}}-demo-app
        server: 'https://kubernetes.default.svc'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true