{{- if .Values.cert.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: backstage-certificate
spec:
  secretName: backstage-tls
  issuerRef:
    name: {{ .Values.cert.issuerRef }}
    kind: ClusterIssuer
  dnsNames:
    - {{ .Values.backstage.ingress.host }}
{{- end }}
