kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Values.name }}-ingress
  labels:
    app: {{ .Values.name }}
spec:
  {{- with .Values.ingressClassName }}
  ingressClassName: {{ . }}
  {{- end }}
  rules:
    - host:  {{ .Values.backstage.hostname }}
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name:  {{ .Values.name }}-service
                port:
                  number: {{ .Values.backstage.port }}
  tls:
  - hosts:
      - {{ .Values.backstage.hostname }}
    secretName: {{ .Values.name }}-certificate

