apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
  labels: 
    app: {{ .Values.name }}
spec:
  ports:
    - port: {{ .Values.backstage.port }}
      targetPort: {{ .Values.backstage.backend }}
      protocol: TCP
      name: http-backend
  selector:
    app: {{ .Values.name }}
  type: ClusterIP
