vui:
  global:
    veleroNamespace: velero
    kubernetesClusterDomain: cluster.local
    clusterName: "suxessit--lab"

  apiConfig:
    apiEnableDocumentation: "1"
    awsAccessKeyId: minio
    awsSecretAccessKey: minio123
    k8SInClusterMode: "True"
    origins1: 'https://velero-ui.lab.suxessit.k8s.cloud.uibk.ac.at'
    securityTokenKey: 39ed3a846cf9fb105cbab6df007f5b7afbd163dbe66aaa19fafd25eb6fe0723a
    veleroCliVersion: v1.13.2
    defaultAdminUsername: admin
    defaultAdminPassword: admin

  uiIngress:
    enabled: true
    host: velero-ui.lab.suxessit.k8s.cloud.uibk.ac.at
    ingressClassName: nginx
    metadata:
      annotations:
        cert.gardener.cloud/purpose: managed
        dns.gardener.cloud/class: garden
        dns.gardener.cloud/dnsnames: velero-ui.lab.suxessit.k8s.cloud.uibk.ac.at
        dns.gardener.cloud/ttl: "180"
    spec:
      tls:
        - secretName: velero-ui-tls
          hosts:
            - velero-ui.lab.suxessit.k8s.cloud.uibk.ac.at
  
  uiNp: # NodePort
    enabled: false
    ip: ""
    apiPort: "30001"
    uiPort: "30002"

