apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Values.deployments.keycloak.service.name }}"
  annotations:
    # for operator
    #nginx.ingress.kubernetes.io/backend-protocol: HTTPS 
    # for dev
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
#    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
#    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
spec:
  tls:
    - hosts:
        - "{{ .Values.deployments.ingress.host }}"
      secretName: "{{ .Values.secrets.tls.name }}"
  rules:
    - host: "{{ .Values.deployments.ingress.host }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ .Values.deployments.keycloak.service.name }}"
                port:
                  number: {{.Values.deployments.keycloak.ports.containerPort}}
