{{- if .Values.datasources.enabled }}
{{- range $sources := .Values.datasources.sources }}
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: {{ $sources.name }}
  namespace: kubevirt
spec:
  source:
    http:
      url: "{{ $sources.url }}"
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: {{ $sources.storage }}
{{ end }}
{{- end }}
