{{- if .Values.datasources.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubevirt-datavolume-permission
rules:
- apiGroups: ["cdi.kubevirt.io"]
  resources: ["volumeclonesources"]
  verbs: ["get","update","list","watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-clone-to-clientnamespace-sa-default
  namespace: kubevirt
subjects:
{{- range $sources := .Values.datasources.clientnamespaces }}
- kind: ServiceAccount
  name: default
  namespace: {{ $sources }}
{{- end }}
roleRef:
  kind: ClusterRole
  name: kubevirt-datavolume-permission
  apiGroup: rbac.authorization.k8s.io
{{- end }}
