# for vms only
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: approved-application-team-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  ignoreDifferences:
    - group: backstage.io
      jsonPointers:
        - /metadata/description
      kind: System
  project: default
  source:
    directory:
      include: 'team-app/*.yaml'
      jsonnet: {}
      recurse: true
    path: .
    repoURL: 'https://github.com/suxess-it/approved-application.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m
    syncOptions:
      - Validate=false
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
