## Using default values from https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml
##
grafana:
  adminPassword: prom-operator
  # set cookies for backstage plugin integration
  grafana.ini:
    security:
      allow_embedding: 'true'
      cookie_samesite: none
      cookie_secure: 'true'
  ingress:
    ## If true, Grafana Ingress will be created
    ##
    enabled: true
    ingressClassName: nginx
    annotations:
      cert.gardener.cloud/purpose: managed
      dns.gardener.cloud/class: garden
      dns.gardener.cloud/dnsnames: grafana.lab-jokl.suxessit.k8s.cloud.uibk.ac.at
      dns.gardener.cloud/ttl: "180"
    hosts: [grafana.lab-jokl.suxessit.k8s.cloud.uibk.ac.at]
    tls:
      - secretName: grafana-server-tls
        hosts:
        - grafana.lab-jokl.suxessit.k8s.cloud.uibk.ac.at
        
  # # To make Grafana persistent (Using Statefulset)
  # #
  persistence:
    enabled: true
    type: sts
    accessModes:
      - ReadWriteOnce
    size: 1Gi
    finalizers:
      - kubernetes.io/pvc-protection

  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      searchNamespace: ALL
      multicluster:
        global:
          enabled: true
    datasources:
      enabled: true
      label: grafana_datasource
      labelValue: "1"
      searchNamespace:
        - grafana
        - mimir
        - loki

  defaultDashboardsEditable: true

  # Provision grafana-dashboards-kubernetes
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'grafana-dashboards-kubernetes'
        orgId: 1
        folder: 'dotdc-Kubernetes'
        type: file
        disableDeletion: true
        editable: true
        options:
          path: /var/lib/grafana/dashboards/grafana-dashboards-kubernetes
  dashboards:
    grafana-dashboards-kubernetes:
      k8s-system-api-server:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-api-server.json
        token: ''
      k8s-system-coredns:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-coredns.json
        token: ''
      k8s-views-global:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-global.json
        token: ''
      k8s-views-namespaces:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-namespaces.json
        token: ''
      k8s-views-nodes:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-nodes.json
        token: ''
      k8s-views-pods:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-pods.json
        token: ''
  
