apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sx-argocd
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jkleinlercher/cnp-local-demo
    targetRevision: main
    path: platform-apps/argocd
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true