apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sx-argo-rollouts
  namespace: argo-rollouts
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jkleinlercher/cnp-local-demo
    targetRevision: main
    path: platform-apps/argo-rollouts
  destination:
    namespace: argo-rollouts
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
