apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sx-backstage
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io  
spec:
  project: default
  source:
    repoURL: https://github.com/jkleinlercher/cnp-local-demo
    targetRevision: main
    path: platform-apps/backstage
  destination:
    namespace: backstage
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true