apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sx-kyverno
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jkleinlercher/cnp-local-demo
    targetRevision: main
    path: platform-apps/kyverno
  destination:
    namespace: kyverno
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Replace=true
