apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sx-team-apps
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/suxess-it/sx-cnp-oss
    targetRevision: main
    path: team-apps
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
