# This is a basic workflow to help you get started with Actions

name: test sx-cnp-oss k3d stack on kind cluster

# Controls when the workflow will run
on:
  # at he moment this action only works when pushed to main because all references in the scripts and argocd apps use the main branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1
        with:
          cluster_name: sx-cnp-oss-cluster
